server:
  port: 7399
  tomcat:
    max-http-form-post-size: -1

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:33060/jdbcstudy
#
#    username: root
#
#    password: DST773344

#关闭模板引擎的我缓存
spring:
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
  #    prefix: classpath:templates/emp/
#配置文件存放的真实位置
  messages:
    basename: i18n.login

  mvc:
    static-path-pattern: /static/**


#    favicon:
#      enabled: false